<#
.SYNOPSIS
  Creates deploy/keycloak/.env from env.example with interactive prompts.

.DESCRIPTION
  Run from the repository root. Does not deploy anything; only prepares secrets
  next to deploy/keycloak/docker-compose.yml.
#>
#Requires -Version 5.1
param()

$ErrorActionPreference = "Stop"
$repoRoot = Resolve-Path (Join-Path $PSScriptRoot "..\..")
$keycloakDir = Join-Path $repoRoot "deploy\keycloak"
$example = Join-Path $keycloakDir "env.example"
$target = Join-Path $keycloakDir ".env"

if (-not (Test-Path $example)) {
    throw "Missing template at '$example'."
}

if (Test-Path $target) {
    Write-Host "File already exists: $target"
    $overwrite = Read-Host "Overwrite? (y/N)"
    if ($overwrite -ne "y" -and $overwrite -ne "Y") {
        Write-Host "Leaving existing .env unchanged."
        return
    }
}

Write-Host "Enter values for Keycloak production (.env). Press Enter to accept [defaults] where shown."
$hostname = Read-Host "KEYCLOAK_HOSTNAME (public URL, e.g. https://auth.mybudget.example.com)"
if ([string]::IsNullOrWhiteSpace($hostname)) {
    throw "KEYCLOAK_HOSTNAME is required."
}

$httpPort = Read-Host "KEYCLOAK_HTTP_PORT [8080]"
if ([string]::IsNullOrWhiteSpace($httpPort)) { $httpPort = "8080" }

$adminUser = Read-Host "KEYCLOAK_ADMIN_USERNAME [admin]"
if ([string]::IsNullOrWhiteSpace($adminUser)) { $adminUser = "admin" }

$adminPass = Read-Host "KEYCLOAK_ADMIN_PASSWORD" -AsSecureString
$adminPlain = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
    [Runtime.InteropServices.Marshal]::SecureStringToBSTR($adminPass))
if ([string]::IsNullOrWhiteSpace($adminPlain)) {
    throw "KEYCLOAK_ADMIN_PASSWORD is required."
}

$dbPass = Read-Host "KEYCLOAK_DB_PASSWORD" -AsSecureString
$dbPlain = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
    [Runtime.InteropServices.Marshal]::SecureStringToBSTR($dbPass))
if ([string]::IsNullOrWhiteSpace($dbPlain)) {
    throw "KEYCLOAK_DB_PASSWORD is required."
}

$lines = @(
    "# Generated by New-KeycloakDeploymentPackage.ps1",
    "KEYCLOAK_HOSTNAME=$hostname",
    "KEYCLOAK_HTTP_PORT=$httpPort",
    "KEYCLOAK_ADMIN_USERNAME=$adminUser",
    "KEYCLOAK_ADMIN_PASSWORD=$adminPlain",
    "KEYCLOAK_DB_PASSWORD=$dbPlain"
)

[System.IO.File]::WriteAllLines($target, $lines, [System.Text.UTF8Encoding]::new($false))
Write-Host "Wrote $target"
Write-Host "Next: deploy with Deploy-MyBudgetKeycloak.ps1 or Portainer UI (see deploy/SYNOLOGY-KEYCLOAK.md)."
