<#
.SYNOPSIS
  Creates deploy/synology/.env and ui-config.json for the full-stack compose file.

.DESCRIPTION
  Run from the repository root. Does not deploy; only prepares secrets next to
  deploy/synology/docker-compose.yml for Container Manager or SSH + docker compose.

.EXAMPLE
  pwsh ./deploy/synology/New-SynologyDeploymentPackage.ps1
#>
#Requires -Version 7.0
param()

$ErrorActionPreference = "Stop"
$here = $PSScriptRoot
$synologyDir = $here
$example = Join-Path $synologyDir "env.example"
$targetEnv = Join-Path $synologyDir ".env"
$uiConfig = Join-Path $synologyDir "ui-config.json"

if (-not (Test-Path (Join-Path $synologyDir "docker-compose.yml"))) {
    throw "Missing deploy/synology/docker-compose.yml."
}
if (-not (Test-Path $example)) {
    throw "Missing deploy/synology/env.example."
}

Write-Host "MyBudget Synology stack — enter production values. Press Enter for [defaults] where shown."

$dbName = Read-Host "POSTGRES_DB [my_budget]"
if ([string]::IsNullOrWhiteSpace($dbName)) { $dbName = "my_budget" }
$dbUser = Read-Host "POSTGRES_USER [mybudget]"
if ([string]::IsNullOrWhiteSpace($dbUser)) { $dbUser = "mybudget" }
$dbPass = Read-Host "POSTGRES_PASSWORD" -AsSecureString
$dbPlain = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
    [Runtime.InteropServices.Marshal]::SecureStringToBSTR($dbPass))
if ([string]::IsNullOrWhiteSpace($dbPlain)) {
    throw "POSTGRES_PASSWORD is required."
}

$apiPort = Read-Host "API_HOST_PORT [5256]"
if ([string]::IsNullOrWhiteSpace($apiPort)) { $apiPort = "5256" }
$uiPort = Read-Host "UI_HOST_PORT [9080]"
if ([string]::IsNullOrWhiteSpace($uiPort)) { $uiPort = "9080" }

Write-Host "--- Keycloak ---"
$kcHost = Read-Host "KEYCLOAK_HOSTNAME (public URL, e.g. https://auth.example.com)"
if ([string]::IsNullOrWhiteSpace($kcHost)) {
    throw "KEYCLOAK_HOSTNAME is required."
}
$kcHttpPort = Read-Host "KEYCLOAK_HTTP_PORT [8080]"
if ([string]::IsNullOrWhiteSpace($kcHttpPort)) { $kcHttpPort = "8080" }
$kcAdminUser = Read-Host "KEYCLOAK_ADMIN_USERNAME [admin]"
if ([string]::IsNullOrWhiteSpace($kcAdminUser)) { $kcAdminUser = "admin" }
$kcAdminPass = Read-Host "KEYCLOAK_ADMIN_PASSWORD" -AsSecureString
$kcAdminPlain = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
    [Runtime.InteropServices.Marshal]::SecureStringToBSTR($kcAdminPass))
if ([string]::IsNullOrWhiteSpace($kcAdminPlain)) {
    throw "KEYCLOAK_ADMIN_PASSWORD is required."
}
$kcDbPass = Read-Host "KEYCLOAK_DB_PASSWORD" -AsSecureString
$kcDbPlain = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
    [Runtime.InteropServices.Marshal]::SecureStringToBSTR($kcDbPass))
if ([string]::IsNullOrWhiteSpace($kcDbPlain)) {
    throw "KEYCLOAK_DB_PASSWORD is required."
}

$defaultIssuer = ($kcHost.TrimEnd("/") + "/realms/my-budget")
Write-Host "--- API / CORS (see README Auth section) ---"
$authEnabled = Read-Host "AUTH_ENABLED [false]"
if ([string]::IsNullOrWhiteSpace($authEnabled)) { $authEnabled = "false" }
$authAuthority = Read-Host "AUTH_AUTHORITY (JWT issuer) [$defaultIssuer]"
if ([string]::IsNullOrWhiteSpace($authAuthority)) { $authAuthority = $defaultIssuer }
$authAudience = Read-Host "AUTH_AUDIENCE [my-budget-api]"
if ([string]::IsNullOrWhiteSpace($authAudience)) { $authAudience = "my-budget-api" }
$authHttpsMeta = Read-Host "AUTH_REQUIRE_HTTPS_METADATA [true]"
if ([string]::IsNullOrWhiteSpace($authHttpsMeta)) { $authHttpsMeta = "true" }
$frontendOrigin = Read-Host "FRONTEND_ORIGIN (CORS, e.g. http://diskstation:9080)"
if ([string]::IsNullOrWhiteSpace($frontendOrigin)) {
    throw "FRONTEND_ORIGIN is required."
}

Write-Host "--- UI (browser must reach the API URL you enter) ---"
$apiBaseHint = "http://<your-host>:$apiPort"
Write-Host "Suggested API base for config.json: $apiBaseHint"
$apiBaseUrl = Read-Host "apiBaseUrl for ui-config.json [$apiBaseHint]"
if ([string]::IsNullOrWhiteSpace($apiBaseUrl)) { $apiBaseUrl = $apiBaseHint }

$uiJson = (@{ apiBaseUrl = $apiBaseUrl } | ConvertTo-Json -Compress)
[System.IO.File]::WriteAllText($uiConfig, $uiJson + [Environment]::NewLine)

$envLines = @(
    "# Generated by New-SynologyDeploymentPackage.ps1",
    "MYBUDGET_API_IMAGE=mybudget-api:local",
    "MYBUDGET_UI_IMAGE=mybudget-ui:local",
    "POSTGRES_DB=$dbName",
    "POSTGRES_USER=$dbUser",
    "POSTGRES_PASSWORD=$dbPlain",
    "API_HOST_PORT=$apiPort",
    "UI_HOST_PORT=$uiPort",
    "AUTH_ENABLED=$authEnabled",
    "AUTH_AUTHORITY=$authAuthority",
    "AUTH_AUDIENCE=$authAudience",
    "AUTH_REQUIRE_HTTPS_METADATA=$authHttpsMeta",
    "FRONTEND_ORIGIN=$frontendOrigin",
    "KEYCLOAK_HOSTNAME=$kcHost",
    "KEYCLOAK_HTTP_PORT=$kcHttpPort",
    "KEYCLOAK_ADMIN_USERNAME=$kcAdminUser",
    "KEYCLOAK_ADMIN_PASSWORD=$kcAdminPlain",
    "KEYCLOAK_DB_PASSWORD=$kcDbPlain"
)
[System.IO.File]::WriteAllText($targetEnv, ($envLines -join [Environment]::NewLine) + [Environment]::NewLine)

Write-Host "Wrote $targetEnv and $uiConfig"
Write-Host "Next: pwsh ./deploy/synology/Deploy-SynologyStack.ps1 -SshUser ... -SshHost ... -RemoteDirectory ..."
