// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyBudget.Api.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyBudget.Api.Infrastructure.Migrations
{
    [DbContext(typeof(BudgetDbContext))]
    [Migration("20260419062640_StorePositionRecurrenceRuleJson")]
    partial class StorePositionRecurrenceRuleJson
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyBudget.Api.Domain.Entities.ActualEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateOnly>("BookedOn")
                        .HasColumnType("date")
                        .HasColumnName("booked_on");

                    b.Property<Guid>("BudgetPositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("budget_position_id");

                    b.Property<string>("ExternalRef")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("external_ref");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.HasKey("Id")
                        .HasName("pk_actual_entries");

                    b.HasIndex("BudgetPositionId")
                        .HasDatabaseName("ix_actual_entries_budget_position_id");

                    b.ToTable("actual_entries", (string)null);
                });

            modelBuilder.Entity("MyBudget.Api.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MyBudget.Api.Domain.Entities.BudgetBaseline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("ForkedFromBaselineId")
                        .HasColumnType("uuid")
                        .HasColumnName("forked_from_baseline_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_baselines");

                    b.HasIndex("ForkedFromBaselineId")
                        .HasDatabaseName("ix_baselines_forked_from_baseline_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_baselines_user_id");

                    b.ToTable("baselines", (string)null);
                });

            modelBuilder.Entity("MyBudget.Api.Domain.Entities.BudgetPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BaselineId")
                        .HasColumnType("uuid")
                        .HasColumnName("baseline_id");

                    b.Property<int>("Cadence")
                        .HasColumnType("integer")
                        .HasColumnName("cadence");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<decimal>("DefaultAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("default_amount");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid?>("ForkedFromPositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("forked_from_position_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<string>("RecurrenceRuleJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("recurrence_rule_json");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("pk_positions");

                    b.HasIndex("BaselineId")
                        .HasDatabaseName("ix_positions_baseline_id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_positions_category_id");

                    b.HasIndex("ForkedFromPositionId")
                        .HasDatabaseName("ix_positions_forked_from_position_id");

                    b.ToTable("positions", (string)null);
                });

            modelBuilder.Entity("MyBudget.Api.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("color");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_user_id_name");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("MyBudget.Api.Domain.Entities.PlannedAmount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<Guid>("BudgetPositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("budget_position_id");

                    b.Property<bool>("IsOverride")
                        .HasColumnType("boolean")
                        .HasColumnName("is_override");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_planned_amounts");

                    b.HasIndex("BudgetPositionId", "Year", "Month")
                        .IsUnique()
                        .HasDatabaseName("ix_planned_amounts_budget_position_id_year_month");

                    b.ToTable("planned_amounts", (string)null);
                });

            modelBuilder.Entity("MyBudget.Api.Domain.Entities.ActualEntry", b =>
                {
                    b.HasOne("MyBudget.Api.Domain.Entities.BudgetPosition", "BudgetPosition")
                        .WithMany("ActualEntries")
                        .HasForeignKey("BudgetPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_actual_entries_positions_budget_position_id");

                    b.Navigation("BudgetPosition");
                });

            modelBuilder.Entity("MyBudget.Api.Domain.Entities.BudgetBaseline", b =>
                {
                    b.HasOne("MyBudget.Api.Domain.Entities.BudgetBaseline", "ForkedFromBaseline")
                        .WithMany("Forks")
                        .HasForeignKey("ForkedFromBaselineId")
                        .HasConstraintName("fk_baselines_baselines_forked_from_baseline_id");

                    b.HasOne("MyBudget.Api.Domain.Entities.AppUser", "User")
                        .WithMany("Baselines")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_baselines_users_user_id");

                    b.Navigation("ForkedFromBaseline");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyBudget.Api.Domain.Entities.BudgetPosition", b =>
                {
                    b.HasOne("MyBudget.Api.Domain.Entities.BudgetBaseline", "Baseline")
                        .WithMany("Positions")
                        .HasForeignKey("BaselineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_positions_baselines_baseline_id");

                    b.HasOne("MyBudget.Api.Domain.Entities.Category", "Category")
                        .WithMany("BudgetPositions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_positions_categories_category_id");

                    b.HasOne("MyBudget.Api.Domain.Entities.BudgetPosition", "ForkedFromPosition")
                        .WithMany("Forks")
                        .HasForeignKey("ForkedFromPositionId")
                        .HasConstraintName("fk_positions_positions_forked_from_position_id");

                    b.Navigation("Baseline");

                    b.Navigation("Category");

                    b.Navigation("ForkedFromPosition");
                });

            modelBuilder.Entity("MyBudget.Api.Domain.Entities.Category", b =>
                {
                    b.HasOne("MyBudget.Api.Domain.Entities.AppUser", "User")
                        .WithMany("Categories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_categories_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyBudget.Api.Domain.Entities.PlannedAmount", b =>
                {
                    b.HasOne("MyBudget.Api.Domain.Entities.BudgetPosition", "BudgetPosition")
                        .WithMany("PlannedAmounts")
                        .HasForeignKey("BudgetPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_planned_amounts_positions_budget_position_id");

                    b.Navigation("BudgetPosition");
                });

            modelBuilder.Entity("MyBudget.Api.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("Baselines");

                    b.Navigation("Categories");
                });

            modelBuilder.Entity("MyBudget.Api.Domain.Entities.BudgetBaseline", b =>
                {
                    b.Navigation("Forks");

                    b.Navigation("Positions");
                });

            modelBuilder.Entity("MyBudget.Api.Domain.Entities.BudgetPosition", b =>
                {
                    b.Navigation("ActualEntries");

                    b.Navigation("Forks");

                    b.Navigation("PlannedAmounts");
                });

            modelBuilder.Entity("MyBudget.Api.Domain.Entities.Category", b =>
                {
                    b.Navigation("BudgetPositions");
                });
#pragma warning restore 612, 618
        }
    }
}
